# Generated by Django 5.1.4 on 2024-12-16 18:47

import datetime
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
